#! /bin/sh

BSPDIR="$HOME/.config/bspwm"
export PATH="${PATH}:$BSPDIR/scripts"


pgrep -x sxhkd > /dev/null || sxhkd &


bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#5D4C70"
bspc config focused_border_color "#FFC8FB"

if [ "$MODE" == "LAPTOP" ] || [ "$MODE" == "THINKPAD" ]
then
    bspc monitor -d 1 2 3 4 5 6 7 8
else
    MONITOR_ONE=$(xrandr --query | grep -sw 'connected' | grep -sw "DP" | grep -o "^[^ ]*")
    MONITOR_TWO=$(xrandr --query | grep -sw 'connected' | grep -sw "HDMI" | grep -o "^[^ ]*")
    MONITOR_THREE=$(xrandr --query | grep -sw 'connected' | grep -sw "DisplayPort" | grep -o "^[^ ]*")
    xrandr --output $MONITOR_ONE --primary --mode 3840x1200 --rotate normal --output $MONITOR_TWO --mode 1920x1080 --rotate normal --above $MONITOR_ONE --output $MONITOR_THREE --mode 2560x1440 --rotate left --left-of $MONITOR_ONE --left-of $MONITOR_TWO
    bspc monitor $MONITOR_ONE -d 1 2 3 4 5 6 7 8
    bspc monitor $MONITOR_TWO -d "Wall Monitor"
    bspc monitor $MONITOR_THREE -d "Vertical Monitor"
    bspc wm -O $MONITOR_ONE $MONITOR_TWO $MONITOR_THREE
fi

# Startup Applications
picom &
~/.config/scripts/fehbg.sh &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
ksuperkey -e 'Super_L=Super_L|R'
conky &
