#! /bin/sh

BSPDIR="$HOME/.config/bspwm"
export PATH="${PATH}:$BSPDIR/scripts"

xrandr --output DP-4 --primary --mode 3840x1200 --rotate normal --output HDMI-A-2-2 --mode 1920x1080 --rotate normal --above DP-4 --output DisplayPort-2-1 --mode 2560x1440 --rotate left --left-of DP-4 --left-of HDMI-A-2-2

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-A-2-2 -d "Wall Monitor"
bspc monitor DisplayPort-2-1 -d "Vertical Monitor"

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#5D4C70"
bspc config focused_border_color "#FFC8FB"

# Startup Applications
picom &
~/.config/scripts/.fehbg &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
ksuperkey -e 'Super_L=Super_L|R'
bspc wm -O DP-4 HDMI-A-2-2 DisplayPort-2-1
